### ISSUE TITLE
Chief server implementation

### ISSUE THREAD

**Issue by ostapmk** [carexoid/se-lab#12]
Chief is a main server for communication with front-end. Main goal is to create API that fully satisfies requirements from SRS and UX. We gonna user JWT Bearer for authentication and [Flask-HTTPAuth](https://flask-httpauth.readthedocs.io/en/latest/) module.

You can create test user yourself and inject it everywhere (where needed) for testing purposes. `@auth.login_required` underhood will be replaced with proper authorization at the very end. I recommend you to create unit/integration tests alongside with API development, read [Flask Testing](https://flask.palletsprojects.com/en/2.0.x/testing/) documentation how to do it properly (easy though).

Don't do unnecessary job, just required minimum.

**Comment by SophyaTs** [comment]
Friendly Remainder to create unit/integration tests! 

Read the testing requirements [here](https://drive.google.com/drive/folders/1LG6QILE4SlzpPi4SJQvIUohs5Ac3tbO7), in files "Лаба5_Код_Тест_08_11_2021.pdf" and "Тестування_Лаба5.pdf".
