### ISSUE TITLE
Create UX specification

### ISSUE THREAD

**Issue by carexoid** [carexoid/se-lab#3]

**Comment by carexoid** [comment]
Раз діаграмок багато, то може красивіше буде сховати їх в папочку `/diagrams` відносно того, де воно зараз? 
В терміналі в папочці `/ux` просто вот це прогнати для збереження історії в гіті: `mkdir ./diagrams; git mv *.puml ./diagrams`. Ну це так, дрібничка. І можеш ще, буласочка, табличку версій додати в док :point_right: :point_left:

**Comment by carexoid** [comment]
To generate pdf:
`sudo apt install docker`
`docker pull asciidoctor/docker-asciidoctor`
`cd [directory to where my ux.adoc is located]`
`docker run --rm -v $(pwd):/documents/ asciidoctor/docker-asciidoctor asciidoctor-pdf -a allow-uri-read ux.adoc`

**Comment by SophyaTs** [comment]
[ux.pdf](https://github.com/carexoid/se-lab/files/7478837/ux.pdf)
